### PR TITLE
Modifies the scheduling algorithm and sorts by nodes that are most fu…

### PR DESCRIPTION
**Pull request by connorgorman**
…ll first

### CODE REVIEW

**Comment by connorgorman** [comment]
Currently an RFC

**Comment by axqx** [comment]
Could you add unit tests?

**Comment by connorgorman** [comment]
@axqx Definitely. This is a first pass, just to see if the logic even made sense

**Comment by mauri** [comment]
LGTM. Revert format-only changes in to streamline future diff-ing and cherrypicking

**Pull request merged**
